let LMINSTALACION=[
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO307",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO307",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO307",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO307",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO307",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO307",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO307",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO308",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN DOS POSTES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO308",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN DOS POSTES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO308",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN DOS POSTES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO308",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN DOS POSTES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO308",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN DOS POSTES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO307",
		"DESCRIPCION": "INSTALACIÓN DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA102",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA103",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA104",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA105",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA106",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA109",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA111",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA112",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA113",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA114",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA115",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA117",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA117",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA117",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA118",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA118",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA118",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA118",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA119",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA119",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA119",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA120",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA120",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA121",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA121",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA121",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA152",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA153",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA157",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA158",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA159",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA163",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA164",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA165",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA171",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA172",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA202",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA203",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA204",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA205",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA206",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA207",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA208",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA209",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA210",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA211",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA212",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA212-1",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA212-2",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA212-2",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA213",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA214",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA215",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA218",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA218",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA218",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA218",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA219",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA219",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA219",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA219",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA220",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA220",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA221",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA221",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA221",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA222",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA223",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA225",
		"BAREMO": "AHO224",
		"DESCRIPCION": "INSTALACIÓN O RETIRADA DE DETECTORES DE FALLA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA227",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA227",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA227",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA228",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA228",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA229",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA230",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA231",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA232",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA232",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA232",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA245",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA245",
		"BAREMO": "AHO620",
		"DESCRIPCION": "INSTALACIÓN O RETIRO DE MEDIDOR PARA BALANCE DE CARGAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA245",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA245",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA246",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA246",
		"BAREMO": "AHO620",
		"DESCRIPCION": "INSTALACIÓN O RETIRO DE MEDIDOR PARA BALANCE DE CARGAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA246",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA246",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA301",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA302",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA303",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA304",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA306",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA309",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA311",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA312",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA313",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA314",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA315",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA317",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA318",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA320",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA320-1",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA321",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA322",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA323",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA324",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA324-1",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA325",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA326",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA327",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA328",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA329",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA334",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA402_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA402_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA402_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA406_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA411_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA411_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA411_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA412_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA412_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA412_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA413_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA413_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA413_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA417_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA417_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA417_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA418_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA418_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA418_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA419_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA419_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA419_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA420_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA420_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA420_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LA461",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA463",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA464",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA465",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA466",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA467",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA468",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA469",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA471",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "4"
	},
	{
		"ESTRUCTURA": "LA474",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA475",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "4"
	},
	{
		"ESTRUCTURA": "LA476",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA478",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA480",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA481",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO217",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO217",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO217",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR102",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR105",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR111",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR113",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR114",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR115",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR116",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR117",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR120",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR121",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR122",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR123",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR125",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR127",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR127",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR132",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR132",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR133",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR133",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR135",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR135",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR137",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR142",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR143",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR145",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR173",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR183",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "4"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR193",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR202",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR205",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR211",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR213",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR214",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR215",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR216",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR217",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR220",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR221",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR222",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR223",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR225",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR227",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR227",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR232",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR232",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR233",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR233",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR235",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR235",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR237",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR243",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR250",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR251",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR252",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR273",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR274",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR275",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR275",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR276",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR276",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR277",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR277",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR278",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR278",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR279",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR279",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR280",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR280",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR282",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR291",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR292",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR293",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR294",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR295",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR296",
		"BAREMO": "ACO105",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR297",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR297",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR298",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR299",
		"BAREMO": "ACO104",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO. INCLUYE CERCOS DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR301",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR302",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR303",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR304",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR305",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR306",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR307",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR402",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR403",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR404",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR405",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR406",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR407",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR408",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR409",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR412_GUARDA",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR412_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR412_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR412_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR413_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR413_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR413_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR419_35",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR419_15",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "LAR419_BT",
		"BAREMO": "AHO127",
		"DESCRIPCION": "INSTALACIÓN DE TIRANTE (VIENTO",
		"CANT": " ANCLA)"
	},
	{
		"ESTRUCTURA": "AP301",
		"BAREMO": "AP0001",
		"DESCRIPCION": "INSTALACIÓN O CAMBIO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP301",
		"BAREMO": "IHO126",
		"DESCRIPCION": "CAMBIO O INSTALACIÓN DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP302",
		"BAREMO": "AP0001",
		"DESCRIPCION": "INSTALACIÓN O CAMBIO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP302",
		"BAREMO": "IHO126",
		"DESCRIPCION": "CAMBIO O INSTALACIÓN DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP303",
		"BAREMO": "AP0001",
		"DESCRIPCION": "INSTALACIÓN O CAMBIO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP303",
		"BAREMO": "IHO126",
		"DESCRIPCION": "CAMBIO O INSTALACIÓN DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP303",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP307",
		"BAREMO": "AP0001",
		"DESCRIPCION": "INSTALACIÓN O CAMBIO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP307",
		"BAREMO": "IHO126",
		"DESCRIPCION": "CAMBIO O INSTALACIÓN DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP311",
		"BAREMO": "AP0001",
		"DESCRIPCION": "INSTALACIÓN O CAMBIO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP311",
		"BAREMO": "IHO126",
		"DESCRIPCION": "CAMBIO O INSTALACIÓN DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP311",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP312",
		"BAREMO": "AP0001",
		"DESCRIPCION": "INSTALACIÓN O CAMBIO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP312",
		"BAREMO": "IHO126",
		"DESCRIPCION": "CAMBIO O INSTALACIÓN DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP312",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO217",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO129",
		"DESCRIPCION": "INSTALACIÓN O MEJORA TIERRA DE PROTECCIÓN O SERVICIO",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA477",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA510",
		"BAREMO": "AHO217",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA510",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA510",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA652",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA653",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA654",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA655",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA655",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA655",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA663",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA663",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA663",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA663",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA663",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP400",
		"BAREMO": "SHO366",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO MENOR DE 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA675",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA675",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA675",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA675",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA673",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA674",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO217",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO301",
		"DESCRIPCION": "INSTALACIÓN PLACA O MARCAS DE LADOS PARA EQUIPOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA662",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA662",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA659",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA659",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA659",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "BARRAJE",
		"BAREMO": "AHO121",
		"DESCRIPCION": "INSTALACIÓN DE CRUCETA SIMPLE O DOBLE PARA CONDUCTOR DESNUDO EN POSTE EXISTENTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA657",
		"BAREMO": "AHO122",
		"DESCRIPCION": "INSTALACIÓN DE SOPORTE SIMPLE O DOBLE PARA CONDUCTOR AISLADO EN POSTE EXISTENTE",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA657",
		"BAREMO": "AHO218",
		"DESCRIPCION": "INSTALACIÓN DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA657",
		"BAREMO": "AHO222",
		"DESCRIPCION": "INSTALACIÓN DE DESCARGADORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA657",
		"BAREMO": "SHO367",
		"DESCRIPCION": "PASO AÉREO SUBTERRÁNEO IGUAL O MAYOR 120 MM2",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "AHO203",
		"DESCRIPCION": "INSTALAR CONDUCTOR SOBRE 120 MM2 COBRE O SU EQUIVALENTE EN ALUMINIO.",
		"CANT": "20"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO342",
		"DESCRIPCION": "INSTALAR LAS TRES FASES DE CABLE MONOPOLAR DE HASTA 120 MM2 (COBRE O ALUMINIO) DIRECTAMENTE EN TIERRA BT",
		"CANT": "82"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO358",
		"DESCRIPCION": "REALIZAR TERMINAL INTERIOR O EXTERIOR",
		"CANT": " TIPO T O TIPO CODO EN CABLES DE ALUMINIO O COBRE AISLADO EN MT (UNA FASE)"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO353",
		"DESCRIPCION": "REALIZAR MUFA RECTA (UNIÓN RECTA O EMPALME) EN CABLES MT MONOPOLARES. TRES FASES",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "4"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO163",
		"DESCRIPCION": "SELLADO DUCTOS EN CAMARA O CAMARILLA (POR VÍA)",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO605",
		"DESCRIPCION": "OPERACIÓN EN EQUIPOS MT DE DISTRIBUCIÓN SUBTERRÁNEA",
		"CANT": "21"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO324",
		"DESCRIPCION": "RETIRO LAS TRES FASES CABLE MONOPOLAR DE HASTA 120 MM2 (COBRE O ALUMINIO) MT EN DUCTO",
		"CANT": "15"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "AHO211",
		"DESCRIPCION": "RETIRO DE CONDUCTOR AÉREO BT DESNUDO O PRÉ-REUNIDO O ONDUCTOR AISLADO CUALQUIER CAPACIDAD",
		"CANT": "40"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO409",
		"DESCRIPCION": "INSTALACIÓN DE UNA CELDA MODULAR O COMPACTA",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO410",
		"DESCRIPCION": "RETIRO DE UNA CELDA COMPACTA O MODULAR",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO409",
		"DESCRIPCION": "INSTALACIÓN DE UNA CELDA MODULAR O COMPACTA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "AHO129",
		"DESCRIPCION": "INSTALACIÓN O MEJORA TIERRA DE PROTECCIÓN O SERVICIO",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "AHO129",
		"DESCRIPCION": "INSTALACIÓN O MEJORA TIERRA DE PROTECCIÓN O SERVICIO",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "AHO233",
		"DESCRIPCION": "INSPECCIÓN DE EQUIPOS AEREOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO218",
		"DESCRIPCION": "MANTENIMIENTO MENOR CENTRO DE TRANSFORMACION AEREO",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO219",
		"DESCRIPCION": "COLOCACIÓN O PINTADO DE CODIGOS IDENTIFICATIVOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO219",
		"DESCRIPCION": "COLOCACIÓN O PINTADO DE CODIGOS IDENTIFICATIVOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO414",
		"DESCRIPCION": "MANTENIMIENTO INTEGRAL DE CENTRO DE TRANSFORMACION SUBTERRÁNEO",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO155",
		"DESCRIPCION": "CAMBIO O NIVELADO DE MARCO Y TAPA DE CAMARA",
		"CANT": "0.9"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO206",
		"DESCRIPCION": "DEMOLER MANPOSTERIA",
		"CANT": " ALBAÑILERÍA"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "AHO123",
		"DESCRIPCION": "INSTALACIÓN ARMAZÓN SECUNDARIA",
		"CANT": "0.2"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO203",
		"DESCRIPCION": "CONSTRUCCIÓN EN ALBAÑILERIA",
		"CANT": "1.4000000000000001"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO207",
		"DESCRIPCION": "IMPERMEABILIZACIÓN DE TECHOS EN CENTROS DE TRANSFORMACIÓN",
		"CANT": "30.1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO208",
		"DESCRIPCION": "PINTADO INTERIOR DE LOCAL DE CUALQUIER TIPO DE CENTRO DE TRANSFORMACIÓN",
		"CANT": "30.1"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO209",
		"DESCRIPCION": "INSTALACIÓN O SUSTITUCIÓN DE PUERTAS PARA CENTRO DE TRANSFORMACION",
		"CANT": "3.7"
	},
	{
		"ESTRUCTURA": "RMU",
		"BAREMO": "SHO214",
		"DESCRIPCION": "CONSTRUCCIÓN",
		"CANT": " SUSTITUCIÓN DE RED ELÉCTRICA E ILUMINACIÓN CENTRO DE TRANSFORMACION"
	},
	{
		"ESTRUCTURA": ""
	}
]
