let LMRETIRO=[
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "CTR501",
		"BAREMO": "AHO312",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "CTR505",
		"BAREMO": "AHO312",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU500",
		"BAREMO": "AHO312",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU500-1",
		"BAREMO": "AHO312",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU501",
		"BAREMO": "AHO312",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU502",
		"BAREMO": "AHO312",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU502-1",
		"BAREMO": "AHO312",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO313",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU503",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO313",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU504",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO313",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU506",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO313",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO313",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU510-1",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO312",
		"DESCRIPCION": "RETIRO DE ESTRUCTURA Y APARELLAJE PARA UN TRANSFORMADOR EN UN POSTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "CTU520",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA102",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA103",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA104",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA105",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA106",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA109",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA109",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA111",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA112",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA113",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA114",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA115",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA117",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA117",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA117",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA118",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA118",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA118",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA118",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA119",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA119",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA119",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA120",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA120",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA121",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA121",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA121",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA152",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA153",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA157",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA157",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA158",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA159",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA163",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA163",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA164",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA164",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA165",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA165",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA171",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA202",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA203",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA204",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA205",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA206",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA207",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA208",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA209",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA209",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA210",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA210",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA211",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA212",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA212-1",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA212-2",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA212-2",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA213",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA214",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA215",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA218",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA218",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA218",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA218",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA219",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA219",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA219",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA219",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA220",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA220",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA221",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA221",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA221",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA222",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA223",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA225",
		"BAREMO": "AHO224",
		"DESCRIPCION": "INSTALACIÓN O RETIRADA DE DETECTORES DE FALLA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA227",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA227",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA228",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA228",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA229",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA230",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA231",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA232",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA232",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA245",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA245",
		"BAREMO": "AHO620",
		"DESCRIPCION": "INSTALACIÓN O RETIRO DE MEDIDOR PARA BALANCE DE CARGAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA245",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA246",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA246",
		"BAREMO": "AHO620",
		"DESCRIPCION": "INSTALACIÓN O RETIRO DE MEDIDOR PARA BALANCE DE CARGAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA246",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA301",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA302",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA303",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA304",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA306",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA309",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA311",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA312",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA313",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA314",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA315",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA317",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA318",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA320",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA320-1",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA321",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA322",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA323",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA324",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA324-1",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA325",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA326",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA327",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA328",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA329",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA334",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA402_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA402_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA402_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA406_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA411_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA411_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA411_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA412_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA412_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA412_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA413_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA413_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA413_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA417_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA417_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA417_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA418_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA418_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA418_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA419_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA419_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA419_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA420_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA420_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA420_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA461",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA463",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA464",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA465",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA466",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA467",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA468",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA469",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA471",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "4"
	},
	{
		"ESTRUCTURA": "LA474",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA475",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "4"
	},
	{
		"ESTRUCTURA": "LA476",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA478",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA480",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA481",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO220",
		"DESCRIPCION": "RETIRADA DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA508",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO220",
		"DESCRIPCION": "RETIRADA DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA509",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO220",
		"DESCRIPCION": "RETIRADA DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA511",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR102",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR105",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR111",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR113",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR114",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR115",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR116",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR117",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR120",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR121",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR122",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR123",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR125",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR127",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR127",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR132",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR132",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR133",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR133",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR135",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR135",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR137",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR142",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR143",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR145",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR173",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR183",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "4"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LAR190",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR193",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR202",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR205",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR211",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR213",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR214",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR215",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR216",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR217",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR220",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR221",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR222",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR223",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR225",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR227",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR227",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR232",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR232",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR233",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR233",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR235",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR235",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR237",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR243",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR250",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR251",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR252",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LAR273",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR274",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LAR275",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR275",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR276",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR276",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR277",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR277",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR278",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR278",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR279",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR279",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR280",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR280",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR282",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR291",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR292",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR293",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR294",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR295",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR296",
		"BAREMO": "ACO107",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN.",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR297",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR297",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LAR298",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR299",
		"BAREMO": "ACO106",
		"DESCRIPCION": "RETIRO DE CRUCETA ROLLIZA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO INCLUYE CERCO DE PROTECCIONES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR301",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR302",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR303",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR304",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR305",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR306",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR307",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR402",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR403",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR404",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR405",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR406",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR407",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR408",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR409",
		"BAREMO": "AHO238",
		"DESCRIPCION": "TRABAJOS MENORES EN APOYOS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR412_GUARDA",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR412_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR412_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR412_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR413_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR413_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR413_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR419_35",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR419_15",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LAR419_BT",
		"BAREMO": "AHO128",
		"DESCRIPCION": "MANTENIMIENTO O RETIRO DE TIRANTE",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP301",
		"BAREMO": "AP0002",
		"DESCRIPCION": "RETIRO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP301",
		"BAREMO": "IHO127",
		"DESCRIPCION": "RETIRO DE LUMINARIAS Y/O FAROLAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP302",
		"BAREMO": "AP0002",
		"DESCRIPCION": "RETIRO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP302",
		"BAREMO": "IHO127",
		"DESCRIPCION": "RETIRO DE LUMINARIAS Y/O FAROLAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP303",
		"BAREMO": "AP0002",
		"DESCRIPCION": "RETIRO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP303",
		"BAREMO": "IHO127",
		"DESCRIPCION": "RETIRO DE LUMINARIAS Y/O FAROLAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP303",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP307",
		"BAREMO": "AP0002",
		"DESCRIPCION": "RETIRO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP307",
		"BAREMO": "IHO127",
		"DESCRIPCION": "RETIRO DE LUMINARIAS Y/O FAROLAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP311",
		"BAREMO": "AP0002",
		"DESCRIPCION": "RETIRO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP311",
		"BAREMO": "IHO127",
		"DESCRIPCION": "RETIRO DE LUMINARIAS Y/O FAROLAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP311",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP312",
		"BAREMO": "AP0002",
		"DESCRIPCION": "RETIRO DE BRAZO O SOPORTE DE LUMINARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP312",
		"BAREMO": "IHO127",
		"DESCRIPCION": "RETIRO DE LUMINARIAS Y/O FAROLAS",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "AP312",
		"BAREMO": "AHO126",
		"DESCRIPCION": "RETIRO ARMAZÓN SECUNDARIA",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO220",
		"DESCRIPCION": "RETIRADA DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "6"
	},
	{
		"ESTRUCTURA": "LA515",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA477",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA510",
		"BAREMO": "AHO220",
		"DESCRIPCION": "RETIRADA DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA510",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA652",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA653",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA654",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA655",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA655",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA663",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA663",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA663",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "AP400",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA675",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA675",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA675",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA673",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA674",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO220",
		"DESCRIPCION": "RETIRADA DE UN SECCIONALIZADOR O RECONECTADOR (SF6",
		"CANT": " OLEO"
	},
	{
		"ESTRUCTURA": "LA664",
		"BAREMO": "AHO219",
		"DESCRIPCION": "INSTALACIÓN DE SISTEMA DE CONTROL O TELECONTROL PARA SECCIONALIZADORES",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA662",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA662",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA659",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA659",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "BARRAJE",
		"BAREMO": "AHO124",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE PASO (INCLUSO RED COMPACTA)",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": "LA657",
		"BAREMO": "AHO125",
		"DESCRIPCION": "RETIRO DE CRUCETA SIMPLE O DOBLE EN DISPOSICIÓN DE REMATE O DERIVACIÓN",
		"CANT": "2"
	},
	{
		"ESTRUCTURA": "LA657",
		"BAREMO": "AHO221",
		"DESCRIPCION": "RETIRADA DE UN SECCIONADOR AEREO (CUCHILLAS",
		"CANT": " FUSIBLES"
	},
	{
		"ESTRUCTURA": "LA657",
		"BAREMO": "AHO223",
		"DESCRIPCION": "RETIRADA DE DESCARGADRORES DE TENSIÓN",
		"CANT": "3"
	},
	{
		"ESTRUCTURA": "LA657",
		"BAREMO": "SHO368",
		"DESCRIPCION": "RETIRO DE PASO AÉREO SUBTERRÁNEO CUALQUIER SECCION",
		"CANT": "1"
	},
	{
		"ESTRUCTURA": ""
	}
]
